### ISSUE TITLE
Get roster and contract metadata into chat

### ISSUE THREAD

**Issue by jonathanmreiter** [soufianetahiri/Anxun-isoon#1]
I'm working on translating Roster and Sichuan office contracts. Might be cool to use that inferentially with the chat logs.

For instance, there's plenty of support that shutd0wn is the CEO, Wu Haibo. There's reasonable evidence that lengmo might be Zheng Huadong, his CTO.

**Comment by soufianetahiri** [comment]
Your PR are welcome :)
